<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExVnhLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExVnhLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExVnhLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExVnhLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerExVnhLx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ExVnhLx',
    'container.build_id' => 'dc511bf7',
    'container.build_time' => 1753568808,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExVnhLx');
