<?php

namespace ContainerExVnhLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7nm6ONZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7nm6ONZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7nm6ONZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AssignmentApiController::list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AssignmentApiController::list()', 'getAssignmentApiControllerlistService', true],
            'App\\Controller\\AssignmentApiController::getOne' => ['privates', '.service_locator.QegKerO.App\\Controller\\AssignmentApiController::getOne()', 'getAssignmentApiControllergetOneService', true],
            'App\\Controller\\AssignmentApiController::create' => ['privates', '.service_locator._HaEDTy.App\\Controller\\AssignmentApiController::create()', 'getAssignmentApiControllercreateService', true],
            'App\\Controller\\AssignmentApiController::update' => ['privates', '.service_locator.QXn20Lv.App\\Controller\\AssignmentApiController::update()', 'getAssignmentApiControllerupdateService', true],
            'App\\Controller\\AssignmentApiController::delete' => ['privates', '.service_locator.mbeurYE.App\\Controller\\AssignmentApiController::delete()', 'getAssignmentApiControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AssignmentApiController:list' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AssignmentApiController::list()', 'getAssignmentApiControllerlistService', true],
            'App\\Controller\\AssignmentApiController:getOne' => ['privates', '.service_locator.QegKerO.App\\Controller\\AssignmentApiController::getOne()', 'getAssignmentApiControllergetOneService', true],
            'App\\Controller\\AssignmentApiController:create' => ['privates', '.service_locator._HaEDTy.App\\Controller\\AssignmentApiController::create()', 'getAssignmentApiControllercreateService', true],
            'App\\Controller\\AssignmentApiController:update' => ['privates', '.service_locator.QXn20Lv.App\\Controller\\AssignmentApiController::update()', 'getAssignmentApiControllerupdateService', true],
            'App\\Controller\\AssignmentApiController:delete' => ['privates', '.service_locator.mbeurYE.App\\Controller\\AssignmentApiController::delete()', 'getAssignmentApiControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AssignmentApiController::list' => '?',
            'App\\Controller\\AssignmentApiController::getOne' => '?',
            'App\\Controller\\AssignmentApiController::create' => '?',
            'App\\Controller\\AssignmentApiController::update' => '?',
            'App\\Controller\\AssignmentApiController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AssignmentApiController:list' => '?',
            'App\\Controller\\AssignmentApiController:getOne' => '?',
            'App\\Controller\\AssignmentApiController:create' => '?',
            'App\\Controller\\AssignmentApiController:update' => '?',
            'App\\Controller\\AssignmentApiController:delete' => '?',
        ]);
    }
}
