<?php

namespace ContainerExVnhLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignmentApiControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QXn20Lv.App\Controller\AssignmentApiController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QXn20Lv.App\\Controller\\AssignmentApiController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assignment' => ['privates', 'App\\Entity\\Assignment', 'getAssignmentService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'assignment' => 'App\\Entity\\Assignment',
            'em' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]))->withContext('App\\Controller\\AssignmentApiController::update()', $container);
    }
}
