<?php

namespace ContainerExVnhLx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Assignment' shared autowired service.
     *
     * @return \App\Entity\Assignment
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Assignment.php';

        return $container->privates['App\\Entity\\Assignment'] = new \App\Entity\Assignment();
    }
}
